exp_dir: subset2
output_dir: /home/soham/Master_Thesis/plots/exp/
skip_priors:
  - bad-bad
  - bad-good
save_suffix: exp_naive_good-good
skip_opt:
  - NepsMOASHABO
  - NepsPriMO
  - NepsMOPriorband
  - NepsPiBORW
which_labels: "1"
which_plots:
  - hv
  - pareto
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4