exp_dir: subset2
output_dir: /home/soham/Master_Thesis/plots/exp/
skip_priors:
  - bad-good
  - bad-bad
save_suffix: subset2_good-good
skip_opt:
  - NepsMOASHA
  - NepsMOASHABO
  - NepsPriorMOASHA
which_labels: "1"
which_plots:
  - hv
  - pareto
  - ov_rank
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4