yaml_files:
  - configs/plot_configs/exp/exp_ws_subset12_goodgood.yaml
  - configs/plot_configs/exp/exp_ws_subset12_ovbad.yaml
  - configs/plot_configs/exp/exp_ws_subset12_ovall.yaml
output_dir: /home/soham/Master_Thesis/plots/ws/
save_suffix: exp_ws_all_rankings
file_type: pdf
figsize:
  - 18
  - 6
sub_labels:
  - good-good
  - overall-bad
  - overall-all
remove_prior_annots: true