exp_dir: subset12_merge
output_dir: /home/soham/Master_Thesis/plots/exp/
skip_non_avg: true
priors_to_avg:
  - good-good
  - bad-good
  - bad-bad
avg_prior_label: overall-all
save_suffix: subset12_robust_ov_all
# skip_opt:
#   - RandomSearchWithPriors
which_labels: "1"
which_plots:
  - hv
  - pareto
  - ov_rank
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4