exp_dir: subset12_merge
output_dir: /home/soham/Master_Thesis/plots/exp/
skip_non_avg: true
priors_to_avg:
  - good-good
  - bad-bad
avg_prior_label: overall-extreme
save_suffix: subset12_robust_ov_ex
  - RandomSearchWithPriors
  - Nevergrad_EvolutionStrategy
which_labels: "1"
which_plots:
  - hv
  - pareto
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4