exp_dir: singleobj_mfbo
output_dir: /home/soham/Master_Thesis/ICLR/plots/SO
save_suffix: so_mfbo_comp_overall
priors_to_avg:
  - good
  - bad
avg_prior_label: overall
skip_non_avg: true
which_labels: SO
file_type: pdf
skip_benchmarks:
  - mfh6_good
skip_opt:
  - NepsPriorband
which_plots:
  - perf
  - rank
  - ov_rank
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4
  - fig_size=(20,10)