exp_dir: subset1_100
output_dir: /home/soham/Master_Thesis/plots/misc/
skip_priors:
  - bad-good
  - bad-bad
save_suffix: speed_up_WMT_100_goodgood
skip_opt:
  - RandomSearchWithPriors
  - RandomSearch
  - NepsHyperbandRW
  - Nevergrad_EvolutionStrategy
which_labels: "1"
which_plots:
  - hv
  - pareto
file_type: pdf
specific_fig_params:
  - legend_fontsize=10
  - title_fontsize=10
  - fig_size=(7,5)
  - xylabel_fontsize=15
  - ovrank_xsize=6
  - ovrank_ysize=4
  - bbox_to_anchor=(0.5, -0.08)
which_benchmarks: pd1-translate_wmt-xformer_translate-64
prior_annotations: null