exp_dir: bo_comp_25
output_dir: /home/soham/Master_Thesis/plots/test/
# skip_non_avg: true
# priors_to_avg:
#   - bad-good
#   - bad-bad
# avg_prior_label: overall-bad
skip_opt:
  - NepsMOASHABO
skip_priors:
  - good-good
  - bad-good
save_suffix: subset12_badbad_ablation
# skip_opt:
#   - RandomSearchWithPriors
which_labels: "1"
which_plots:
  - hv
  - pareto
  - ov_rank
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4