yaml_files:
  - configs/plot_configs/appendix/ablation_init_goodgood.yaml
  - configs/plot_configs/appendix/ablation_init_ov_bad.yaml
  - configs/plot_configs/appendix/ablation_init_ov_all.yaml
output_dir: /home/soham/Master_Thesis/plots/appendix_ablation/
save_suffix: ablation_init_all_ranks
file_type: pdf
figsize:
  - 18
  - 6
sub_labels:
  - good-good
  - overall-bad
  - overall-all
# Do not remove prior annotations for this plot since it removes based on brackets, which contain the init hps in this case