exp_dir: momfbo_vs_algo
output_dir: /home/soham/Master_Thesis/plots/appendix_extra/
skip_non_avg: true
priors_to_avg:
  - bad-good
  - bad-bad
avg_prior_label: overall-bad
save_suffix: momfbo_comp_ov_bad
which_labels: "1"
which_plots:
  - hv
  - pareto
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4