exp_dir: subset1
output_dir: /home/soham/Master_Thesis/plots/appendix_extra/
skip_priors:
  - good-good
  - bad-good
save_suffix: addexp_subset1_bad-bad
skip_opt:
  - RandomSearchWithPriors
which_labels: "1"
which_plots:
  - hv
  - pareto
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4
  - bbox_to_anchor=(0.5, -0.08)