exp_dir: subset2
output_dir: /home/soham/Master_Thesis/plots/appendix_extra/
skip_priors:
  - good-good
  - bad-good
save_suffix: addexp_subset2_bad-bad
skip_opt:
  - NepsMOASHA
  - NepsMOASHABO
  - NepsPriorMOASHA
which_labels: "1"
which_plots:
  - hv
  - pareto
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4