yaml_files:
  - configs/plot_configs/appendix/addexp_momfbo_goodgood.yaml
  - configs/plot_configs/appendix/addexp_momfbo_ov_bad.yaml
  - configs/plot_configs/appendix/addexp_momfbo_ov_all.yaml
output_dir: /home/soham/Master_Thesis/plots/appendix_extra/
save_suffix: momfbo_comp_all_ranks
file_type: pdf
figsize:
  - 18
  - 6
sub_labels:
  - good-good
  - overall-bad
  - overall-all
remove_prior_annots: true