exp_dir: subset1_100
output_dir: /home/soham/Master_Thesis/plots/appendix_extra/
skip_priors:
  - bad-good
  - bad-bad
save_suffix: addexp_subset1_100_good-good
skip_opt:
  - RandomSearchWithPriors
  - RandomSearch
  - NepsHyperbandRW
which_labels: "1"
which_plots:
  - hv
  - pareto
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4
  - bbox_to_anchor=(0.5, -0.08)