exp_dir: subset12_merge
output_dir: /home/soham/Master_Thesis/plots/appendix_extra/
priors_to_avg:
  - bad-good
  - bad-bad
skip_non_avg: true
save_suffix: true_pareto_momfpark_ov_bad
skip_opt:
  - RandomSearchWithPriors
  - RandomSearch
  - Nevergrad_EvolutionStrategy
  - NepsHyperbandRW
  - SMAC_ParEGO
which_labels: "1"
which_plots:
  # - hv
  - pareto
  # - ov_rank
which_benchmarks:
  - MOMFPark
plot_true_pareto: true
fixed_pareto_seed: 383329928
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4
  - bbox_to_anchor=(0.5, -0.08)