benchmarks:
  jahs-CIFAR10:
    - valid_acc
    - runtime
  jahs-ColorectalHistology:
    - valid_acc
    - runtime
  jahs-FashionMNIST:
    - valid_acc
    - runtime
prior_spec:
  - [good, 0, 0.01, null]
  - [medium, 0, 0.125, null]
  - [bad, -1, 0, null]