benchmarks:
  - jahs-CIFAR10: valid_acc
  - jahs-CIFAR10: runtime
  - jahs-ColorectalHistology: valid_acc
  - jahs-ColorectalHistology: runtime
  - jahs-FashionMNIST: valid_acc
  - jahs-FashionMNIST: runtime
prior_spec:
  - [good, 0, 0.01, null]
  - [medium, 0, 0.125, null]
  - [bad, -1, 0, null]