benchmarks:
  yahpo-lcbench-126026:
    - val_accuracy
    - val_cross_entropy
    - val_balanced_accuracy
    - time
  yahpo-lcbench-167190:
    - val_accuracy
    - val_cross_entropy
    - val_balanced_accuracy
    - time
  yahpo-lcbench-168330:
    - val_accuracy
    - val_cross_entropy
    - val_balanced_accuracy
    - time
  yahpo-lcbench-168910:
    - val_accuracy
    - val_cross_entropy
    - val_balanced_accuracy
    - time
  yahpo-lcbench-189906:
    - val_accuracy
    - val_cross_entropy
    - val_balanced_accuracy
    - time
prior_spec:
  - [good, 0, 0.01, null]
  - [medium, 0, 0.125, null]
  - [bad, -1, 0, null]