exp_dir: subset1
output_dir: /home/soham/Master_Thesis/ICLR/plots/intro/
skip_non_avg: true
priors_to_avg:
  - good-good
  - bad-good
  - bad-bad
  - good-bad
avg_prior_label: overall
save_suffix: overall
skip_opt:
  - RandomSearchWithPriors
  - RandomSearch
  - Nevergrad_EvolutionStrategy
  # - SMAC_ParEGO
  - NepsHyperbandRW
skip_bench:
  - MOMFPark
which_labels: intro
which_plots:
  - ov_rank
specific_fig_params:
  - ovrank_xsize=6
  - ovrank_ysize=4
  - bbox_to_anchor=(0.5, -0.08)
prior_annotations: null
plot_type: ov_rank