exp_dir: subset1
output_dir: /home/soham/Master_Thesis/plots/intro/
skip_priors:
  - bad-good
  - bad-bad
save_suffix: good-good
skip_opt:
  - RandomSearchWithPriors
  - RandomSearch
  - Nevergrad_EvolutionStrategy
  # - SMAC_ParEGO
  - NepsHyperbandRW
which_labels: intro
which_plots: ov_rank
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4
  - legend_fontsize=15
prior_annotations: null