exp_dir: ablation_init_20
output_dir: /home/soham/Master_Thesis/plots/ICLR/exp/
save_suffix: ablation_init_all_good
skip_priors:
  - bad-good
  - bad-bad
  - good-bad
skip_bench:
  - MOMFPark
which_labels: ablation_init
which_plots:
  - hv
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4