yaml_files:
  - configs/paper_configs/exp/ablation_algos_overall.yaml
  - configs/paper_configs/exp/ablation_algos_all_good.yaml
  - configs/paper_configs/exp/ablation_algos_mixed.yaml
  - configs/paper_configs/exp/ablation_algos_all_bad.yaml
output_dir: /home/soham/Master_Thesis/ICLR/plots/exp/
save_suffix: ablation_algos_all_ranks
file_type: pdf
figsize:
  - 16
  - 4
sub_labels:
  - Overall
  - All priors good
  - Mixed priors
  - All priors bad
remove_prior_annots: true
ylim: 5