exp_dir: subset1
output_dir: /home/soham/Master_Thesis/ICLR/plots/exp/
skip_non_avg: true
priors_to_avg:
  - good-good
  - bad-good
  - bad-bad
  - good-bad
avg_prior_label: overall
save_suffix: subset1_overall
skip_opt:
  - RandomSearchWithPriors
skip_bench:
  - MOMFPark
which_labels: "1"
which_plots:
  - hv
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4
  - bbox_to_anchor=(0.5, -0.08)
figsize:
  - 20
  - 10