exp_dir: subset1
output_dir: /home/soham/Master_Thesis/ICLR/plots/exp/
skip_priors:
  - bad-good
  - bad-bad
  - good-bad
save_suffix: subset1_all_good
skip_opt:
  - RandomSearchWithPriors
skip_bench:
  - MOMFPark
which_labels: "1"
which_plots:
  - hv
  - pareto
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4
  - bbox_to_anchor=(0.5, -0.08)
figsize:
  - 20
  - 10