exp_dir: subset2
output_dir: /home/soham/Master_Thesis/ICLR/plots/exp/
skip_non_avg: true
priors_to_avg:
  - good-good
  - bad-good
  - bad-bad
  - good-bad
avg_prior_label: overall
save_suffix: subset2_overall
skip_opt:
  - NepsMOASHA
  - NepsMOASHABO
  - NepsPriorMOASHA
skip_bench:
  - MOMFPark
which_labels: "1"
which_plots:
  - hv
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4
figsize:
  - 20
  - 10