yaml_files:
  - configs/paper_configs/exp/exp_subset1_overall.yaml
  - configs/paper_configs/exp/exp_subset1_all_good.yaml
  - configs/paper_configs/exp/exp_subset1_mixed.yaml
  - configs/paper_configs/exp/exp_subset1_all_bad.yaml
output_dir: /home/soham/Master_Thesis/ICLR/plots/exp/
save_suffix: exp_subset1_all_rankings
file_type: pdf
figsize:
  - 24
  - 6
sub_labels:
  - overall
  - all-good
  - mixed
  - all-bad
remove_prior_annots: true