exp_dir: subset12_merge
output_dir: /home/soham/Master_Thesis/plots/sig_analysis/
skip_priors:
  - bad-good
  - bad-bad
save_suffix: cd_plots_subset12_good-good_10
skip_opt:
  # - RandomSearchWithPriors
  # - RandomSearch
  # - SMAC_ParEGO
  # - Nevergrad_EvolutionStrategy
  # - NepsHyperbandRW
  # - NepsRW
  # - NepsMOASHA
which_labels: "sig"