yaml_files:
  - configs/plot_configs/sig/cd_subset12_goodgood.yaml
  - configs/plot_configs/sig/cd_subset12_ov_bad.yaml
  - configs/plot_configs/sig/cd_subset12_ov_all.yaml
output_dir: /home/soham/Master_Thesis/plots/sig_analysis/
save_suffix: all_cd_plots_10
file_type: pdf
figsize:
  - 18
  - 6
sub_labels:
  - good-good
  - overall-bad
  - overall-all
remove_prior_annots: true
at_iteration: 10
normalize_hv: true