exp_dir: eps_study
output_dir: /home/soham/Master_Thesis/NeurIPS/plots/extra/
skip_priors:
  - good-good
  - bad-good
  - good-bad
save_suffix: eps_study_all_bad
# which_labels: "1"
which_plots:
  - hv
specific_fig_params:
  - bbox_to_anchor=(0.5, -0.12)
figsize:
  - 8
  - 8