yaml_files:
  - configs/paper_configs/extra/hwgptbench_3obj_overall.yaml
  - configs/paper_configs/extra/hwgptbench_3obj_all_good.yaml
  - configs/paper_configs/extra/hwgptbench_3obj_mixed.yaml
  - configs/paper_configs/extra/hwgptbench_3obj_all_bad.yaml
output_dir: /home/soham/Master_Thesis/NeurIPS/plots/extra/
save_suffix: hwgpt_s_3o_all_rankings
file_type: pdf
figsize:
  - 28
  - 4
sub_labels:
  - Overall
  - All priors good
  - Mixed priors
  - All priors bad
remove_prior_annots: true
ylim: 7
cut_off_iteration: 20
tight_layout: false
wspace: 0.5