exp_dir: ablation1_25
output_dir: /home/soham/Master_Thesis/plots/appendix_ablation/
save_suffix: ablation_design_ov-all
avg_prior_label: overall-all
priors_to_avg:
  - good-good
  - bad-good
  - bad-bad
skip_non_avg: True
which_labels: ablation
which_plots:
  - hv
  - pareto
  - ov_rank
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4