optimizers:
  - name: RandomSearchWithPriors
    hps:
      mo_prior_sampling: random
  - name: RandomSearch
    hps: null
  - name: SMAC_ParEGO
    hps: null
benchmarks:
  - name: MOMFPark
    objs:
      value1: good
      value2: good
  - name: MOMFBraninCurrin
    objs:
      value1: good
      value2: good
seeds: 1
num_iterations: 5