optimizers:
  RandomSearchWithPriors:
    mo_prior_sampling: equal
  RandomSearch: null
benchmarks:
  MOMFPark:
    value1: good
    value2: good
  MOMFBraninCurrin:
    value1: good
    value2: good
seeds: 1
num_iterations: 10