optimizers:
  - name: RandomSearchWithPriors
    hyperparameters:
      mo_prior_sampling: random
  - name: RandomSearch
    hyperparameters: null
  - name: SMAC_ParEGO
    hyperparameters: null
benchmarks:
  - name: MOMFPark
    objectives:
      value1: good
      value2: null
  - name: MOMFBraninCurrin
    objectives:
      value1: good
      value2: good
seeds: 1
num_iterations: 5