optimizers:
  - name: RandomSearchWithPriors
    hyperparameters: 
      mo_prior_sampling: random
benchmarks:
  - name: MOMFPark
    objectives: 
      value1: good
      value2: good
num_seeds: 3
num_iterations: 10