markers:
  good-good: "o"      # Circle
  good-bad: "v"       # Triangle Down
  good-medium: "s"    # Square
  good: "h"      # Hexagon
  bad-good: "^"       # Triangle Up
  bad-bad: "x"        # X
  bad-medium: "d"     # Diamond
  bad: "P"       # Plus (Filled)
  medium-good: "p"    # Pentagon
  medium-bad: "*"     # Star
  medium-medium: "+"  # Plus
  medium: "8"    # Octagon


colors:
  SMAC_ParEGO: blue
  RandomSearch: olivedrab
  RandomSearchWithPriors: red
  NepsRW: lightseagreen
  NepsHyperbandRW: darkgreen
  Nevergrad_EvolutionStrategy: orange
  MOMFBO: purple
