optimizers:
  - name: RandomSearchWithPriors
benchmarks:
  - name: MOMFPark
    objectives:
      value1: good
      value2: good
  - name: MOMFPark
    objectives:
      value1: good
      value2: bad
  - name: MOMFPark
    objectives:
      value1: good
      value2: null
  - name: MOMFPark
    objectives:
      value1: bad
      value2: null
  - name: MOMFPark
    objectives:
      value1: bad
      value2: good
  - name: MOMFPark
    objectives:
      value1: bad
      value2: bad
  - name: MOMFBraninCurrin
    objectives:
      value1: good
      value2: good
  - name: MOMFBraninCurrin
    objectives:
      value1: good
      value2: bad
  - name: MOMFBraninCurrin
    objectives:
      value1: good
      value2: null
  - name: MOMFBraninCurrin
    objectives:
      value1: bad
      value2: null
  - name: MOMFBraninCurrin
    objectives:
      value1: bad
      value2: good
  - name: MOMFBraninCurrin
    objectives:
      value1: bad
      value2: bad
num_seeds: 3
num_iterations: 25