optimizers:
  - name: Nevergrad_EvolutionStrategy
  - name: NepsRW
  - name: NepsHyperbandRW
benchmarks:
  - name: MOMFPark
    objectives: 
      value1: null
      value2: null
num_seeds: 11
num_iterations: 25