optimizers:
  # - name: RandomSearch
  # - name: SMAC_ParEGO
  # - name: NepsRW
  # - name: NepsHyperbandRW
  # - name: Nevergrad_EvolutionStrategy
  # - name: NepsMOASHA
  - name: NepsPiBORW
  # - name: NepsMOASHABO
  # - name: NepsPriMO
benchmarks:
  - name: MOMFPark
    objectives:
      value1: good
      value2: good
  - name: pd1-cifar100-wide_resnet-2048
    objectives:
      valid_error_rate: good
      train_cost: good
  - name: pd1-imagenet-resnet-512
    objectives:
      valid_error_rate: good
      train_cost: good
  - name: pd1-lm1b-transformer-2048
    objectives:
      valid_error_rate: good
      train_cost: good
  - name: pd1-translate_wmt-xformer_translate-64
    objectives:
      valid_error_rate: good
      train_cost: good
  - name: yahpo-lcbench-126026
    objectives:
      val_cross_entropy: good
      time: good
  - name: yahpo-lcbench-146212
    objectives:
      val_cross_entropy: good
      time: good
  - name: yahpo-lcbench-168330
    objectives:
      val_cross_entropy: good
      time: good
  - name: yahpo-lcbench-168868
    objectives:
      val_cross_entropy: good
      time: good
num_seeds: 1
num_iterations: 20