optimizers:
  - name: RandomSearchWithPriors
  - name: NepsRW
  - name: NepsHyperbandRW
benchmarks:
  - name: MOMFPark
    objectives: 
      value1: good
      value2: good
    fidelities: s
  - name: MOMFPark
    objectives: 
      value1: bad
      value2: bad
    fidelities: s
num_seeds: 11
num_iterations: 25