optimizers:
  - name: RandomSearchWithPriors
    hyperparameters: 
      mo_prior_sampling: random
benchmarks:
  - name: MOMFPark
    objectives: 
      value1: null
      value2: null
num_seeds: 5
num_iterations: 10